services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    restart: always
    env_file:
      - .env

  db:
    container_name: my_db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: my_redis
    image: redis:latest
    ports:
      - "6379:6379"
  
volumes:
  db_data:
    driver: local